[project]
name = "container-scan"
version = "2.1.6"
description = "Распознавание и сопоставление номеров контейнеров"
authors = [
    {name = "vanitoo",email = "56897888+vanitoo@users.noreply.github.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<3.16"
dependencies = [
    "opencv-python (>=4.13,<5)",
    "pymupdf (>=1.28,<1.29)",
    "openpyxl (>=3.1.5,<3.2.0)",
    "pytesseract (>=0.3.13,<0.4)",
    "requests (>=2.34,<3)",
    "python-dotenv (>=1.2,<2)",
    "colorama (>=0.4.6,<0.5.0)",
    "numpy (>=2.2,<2.4)",
    "pillow (>=12.3,<13)",
    "sv-ttk (>=2.6.1,<3)"
]

[dependency-groups]
dev = [
    "bandit (>=1.8,<2.0)",
    "pip-audit (>=2.9,<3.0)",
    "pyinstaller (>=6.3,<7.0)",
    "pytest (>=8.0,<10.0)",
    "ruff (>=0.16.4,<1.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "pdf_ocr_app", from = "src"}]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "E", "W", "F", "I", "B", "C4", "EM", "SIM", "PTH", "RUF", "UP"
]
ignore = ["B904", "EM101", "RUF100", "RUF003", "RUF001", "RUF002"]
fixable = ["ALL"]
unfixable = ["F401", "F841"]
extend-ignore = ["RUF001"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["S101"]
